apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ais-minecraft

# For local testing
#commonLabels:
#  kustomize.toolkit.fluxcd.io/reconcile: disabled

resources:
  - gateway.yaml
  - repository.yaml
  - release.yaml

configMapGenerator:
  - name: mc-whitelist
    files:
      - whitelist.txt
    options:
      disableNameSuffixHash: true