apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-prod
  namespace: minecraft
spec:
  releaseName: mc-server
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: itzg
  interval: 50m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/itzg/minecraft-server-charts/blob/master/charts/minecraft/values.yaml
  valuesFrom:
    - kind: ConfigMap
      name: mc-whitelist
      valuesKey: whitelist.txt
      targetPath: minecraftServer.whitelist
  values:
    minecraftServer:
      eula: true
      type: PAPER
      version: "1.21.11"
      difficulty: hard
      memory: 3G
      # G1GC is the best garbage collector for Minecraft
      jvmOpts: "-XX:+UseG1GC -XX:MaxGCPauseMillis=50"
    persistence:
      dataDir:
        enabled: true
        size: 20Gi
